// <auto-generated />
namespace Pinkmeupkt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class new_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "202308290941441_new_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
