// <auto-generated />
namespace Pinkmeupkt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class gc_fix_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gc_fix_2));
        
        string IMigrationMetadata.Id
        {
            get { return "202308291006197_gc_fix_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
